### ISSUE TITLE
Output Munged When Terminal Colors are Defined

### ISSUE THREAD

**Issue by niall-munnelly** [rundeck/rundeck-cli#288]
When RD_COLOR is enabled/true in the rd configuration, like so:

```
export RD_COLOR=1
export RD_COLOR_INFO=blue
export RD_COLOR_WARN=orange
export RD_COLOR_ERROR=cyan
```

The first project will appear with a color code prepended to its name. While this isn't visible when you cat or stdout, it's definitely there:

```
^[[34m# 23 Projects:
^[[0mMy_Project
My_Other_Project
```

Consequently, when using the output of rd projects list in a for-loop, you'll get an error saying that the first project doesn't exist.

The fix is to disable RD_COLOR by setting it to 0 and (presumably) removing or commenting out any color definitions.

**Comment by gschueler** [comment]
i'd recommend setting `RD_COLOR=0` for any use of `rd` in a scripted manner. You can also use `RD_FORMAT=json` or `RD_FORMAT=yaml` to have it output those formats instead of plain text.  I see this page doesn't mention the RD_COLOR variable, but it should: https://rundeck.github.io/rundeck-cli/scripting/
