### ISSUE TITLE
Input error Cannot match project to pattern

### ISSUE THREAD

**Issue by hmalinov** [rundeck/rundeck-cli#306]
Running a the following:
```bash
    for project in $(rd projects list | awk '!/#|^$/'); do
        for job in $(rd jobs list -p "$project" |awk '!/#|^$/ {print $2}'); do
            echo " {\"name\":\"$project: $job\", \"value\":\"$project $job\"},"
        done
    done
```
results in an error:
```bash
Input error for [rd jobs list]: Cannot match (Artifactory) to pattern: [--project -p /^[-_a-zA-Z0-9+][-\._a-zA-Z0-9+]*$/] : Project name
```

However, running :
```bash
rd jobs list -p 'Artifactory'
# 1 Jobs in project Artifactory
2a409ede-eaf0-4e49-b6af-4e35c2012178 configure_replication_for_all_repos
```

This is valid for both Rundeck 2.10 and rd 1.0.14 and for Rundeck 3.2 and rd version 1.3
Any help at least on debugging this would be appreciated.

**Comment by gschueler** [comment]
I ran your script, and hit the same error! The issue is due to the ANSI colorized output.  you can use `RD_COLOR=0` env var to turn off colorization. 

It seems like you are trying to generate some json output? You can also use `RD_FORMAT=json` to get JSON formatted output from rd, which may be more scriptable than using awk, e.g if you use the [jq][] tool. It will also turn off colorization by default

[jq]: https://stedolan.github.io/jq/

I'm not quite sure what you are trying to generate, but it might be something like this:

```sh
(
export RD_FORMAT=json
for project in $(rd projects list | jq -r '.[]'); do
	rd jobs list -p $project -v \
	| jq '.[] | {project, job: (.group+"/"+.name) } | {name: (.project + ": " + .job), value: ( .project + " " + .job ) } ' 
done
) | jq -s '.'
```
the inner section generates a sequence of json objects, and the final `jq -s '.'` combines them into one array.

**Comment by hmalinov** [comment]
Indeed with RD_COLOR=0 , I do not see the error anymore.
I will explore the RD_FORMAT option as well. 

Thank you
