### ISSUE TITLE
`rd projects create` assumes $RUNDECK_BASE is /var/rundeck/

### ISSUE THREAD

**Issue by nbr** [rundeck/rundeck-cli#8]
As a result, if running from the JAR launcher from non `/var/rundeck` path, one is unable to create a new project

**Comment by gschueler** [comment]
`rd` only uses the API to communicate to the server, so it does not matter where you install rundeck for rundeck-cli to work.  if there is an issue creating projects, make sure you server configuration is ok

**Comment by nbr** [comment]
The issue isn't generally creating projects. If I create the directories and place the properties file in the expected location (`/opt/rundeck`), Rundeck recognizes the projects from the GUI.

> make sure you server configuration is ok

Would you be able to specify which configuration? 
In '_rundeck-config.properties_', `rdeck.base=/opt/rundeck`, which is the directory where the JAR was run.

**Comment by gschueler** [comment]
I'm not sure what you are asking or what your problem is.  This sounds like you are having trouble configuring rundeck server, and nothing to do with rundeck-cli.  

what is the error you are getting?  rdeck.base specifies the base for the rundeck install, and for launcher install the `etc` dir under that contains `framework.properties` which defines relevant file paths

**Comment by nbr** [comment]
@gschueler The initial error that I hit indicated that the path `/var/rundeck/` did not exist. It must have been a misconfiguration on my part, since `framework.properties` is consistent/accurate now after provisioning. Sorry for the noise
